version: "3"
services:
  app:
    image: mdsdimat/node-prakt
    depends_on:
      - postgres
      - mongo
    environment:
      DATABASE_URL: postgres://postgres:newPassword@postgres:5432/asteroids
      NODE_ENV: development
      PORT: 9001
    ports:
      - "3000:3000"
    command: >
      bash -c "npm run api:dbsync
      && npm run start"
  app_api:
    image: mdsdimat/node-prakt
    depends_on:
      - postgres
      - mongo
    environment:
      DATABASE_URL: postgres://postgres:newPassword@postgres:5432/asteroids
      NODE_ENV: development
      PORT: 9001
    ports:
      - "9001:9001"
    command: npm run api
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: asteroids
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod
volumes:
  db-data:
