export const REQUESTED_LEADERBOARD = 'REQUESTED_LEADERBOARD';
export const REQUESTED_LEADERBOARD_SUCCEEDED = 'REQUESTED_LEADERBOARD_SUCCEEDED';
export const REQUESTED_LEADERBOARD_FAILED = 'REQUESTED_LEADERBOARD_FAILED';
export const GOT_LEADERBOARD = 'GOT_LEADERBOARD';
