name: CICD

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    env:
      sshkey: ${{ secrets.SSH_PRIVATE_KEY }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with: 
          node-version: 12
     # - name: Instal dependensies
     #   run: npm install

     # - name: Tests
     #  run: echo "no tests" #npm run test

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mdsdimat/node-prakt:latest

      - name: Fetch docker image to server and run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
            docker pull mdsdimat/node-prakt
            docker-compose stop
            docker-compose build
            docker-compose up -d
      #- run: ssh -vvv ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} -i ./github_do.key " && docker pull mdsdimat/node-prakt && docker stop html_app_1 && docker run html_app_1" 
